[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contract = "DvjN1y25fbfFqhXGwnWSTSd6q2Zq8n5inPVoJtT6MHTv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/devnet"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
